"""Plugin-independent playback for the PCM WAV files created by CutVideo."""

from __future__ import annotations

import wave
from dataclasses import dataclass
from pathlib import Path

from PySide6.QtCore import QBuffer, QByteArray, QIODevice, QObject, Signal
from PySide6.QtMultimedia import QAudio, QAudioFormat, QAudioSink, QMediaDevices


class AudioPlaybackError(RuntimeError):
    """Raised when a local preview cannot be sent to the audio device."""


@dataclass(frozen=True, slots=True)
class PcmWavData:
    sample_rate: int
    channels: int
    frames: bytes


def read_pcm16_wav(path: str | Path) -> PcmWavData:
    """Read an uncompressed 16-bit WAV generated by bundled FFmpeg."""

    source = Path(path)
    try:
        with wave.open(str(source), "rb") as reader:
            if reader.getcomptype() != "NONE" or reader.getsampwidth() != 2:
                raise AudioPlaybackError("试听文件不是受支持的 PCM 16-bit WAV")
            sample_rate = reader.getframerate()
            channels = reader.getnchannels()
            frames = reader.readframes(reader.getnframes())
    except AudioPlaybackError:
        raise
    except (EOFError, OSError, wave.Error) as exc:
        raise AudioPlaybackError(f"无法读取试听文件：{source.name}") from exc
    if sample_rate <= 0 or channels <= 0 or not frames:
        raise AudioPlaybackError("试听文件为空或音频参数无效")
    return PcmWavData(sample_rate, channels, frames)


class PcmWavPlayer(QObject):
    """Play PCM samples with ``QAudioSink``, without media codec plugins."""

    finished = Signal()
    failed = Signal(str)
    active_changed = Signal(bool)

    def __init__(self, parent: QObject | None = None) -> None:
        super().__init__(parent)
        self._sink: QAudioSink | None = None
        self._buffer: QBuffer | None = None
        self._bytes: QByteArray | None = None
        self._format_key: tuple[int, int] | None = None
        self._manual_stop = False
        self._playing = False

    @property
    def is_active(self) -> bool:
        return self._playing

    def play(self, path: str | Path) -> None:
        data = read_pcm16_wav(path)
        self.stop()

        audio_format = QAudioFormat()
        audio_format.setSampleRate(data.sample_rate)
        audio_format.setChannelCount(data.channels)
        audio_format.setSampleFormat(QAudioFormat.SampleFormat.Int16)
        device = QMediaDevices.defaultAudioOutput()
        if device.isNull():
            raise AudioPlaybackError("未检测到可用的音频输出设备")
        if not device.isFormatSupported(audio_format):
            raise AudioPlaybackError("当前音频输出设备不支持试听格式")

        format_key = (data.sample_rate, data.channels)
        if self._sink is None or self._format_key != format_key:
            self._dispose_sink()
            self._sink = QAudioSink(device, audio_format, self)
            self._sink.setVolume(0.85)
            sink = self._sink
            sink.stateChanged.connect(
                lambda state, source=sink: self._state_changed(source, state)
            )
            self._format_key = format_key

        self._bytes = QByteArray(data.frames)
        self._buffer = QBuffer(self)
        self._buffer.setData(self._bytes)
        if not self._buffer.open(QIODevice.OpenModeFlag.ReadOnly):
            self._clear()
            raise AudioPlaybackError("无法打开试听缓冲区")

        assert self._sink is not None
        self._manual_stop = True
        self._sink.reset()
        self._manual_stop = False
        self._playing = True
        self._sink.start(self._buffer)
        if self._playing:
            self.active_changed.emit(True)

    def stop(self) -> None:
        if self._sink is None or not self._playing:
            return
        self._manual_stop = True
        self._sink.stop()
        self._manual_stop = False
        self._playing = False
        self._clear_buffer()
        self.active_changed.emit(False)

    def _state_changed(self, sink: QAudioSink, state: QAudio.State) -> None:
        if sink is not self._sink or self._manual_stop:
            return
        if state == QAudio.State.IdleState:
            self._manual_stop = True
            sink.stop()
            self._manual_stop = False
            self._finish_playback()
        elif state == QAudio.State.StoppedState and self._playing:
            error = sink.error()
            at_end = self._buffer is not None and self._buffer.atEnd()
            if _is_natural_completion(error, at_end=at_end):
                self._finish_playback()
                return
            self._playing = False
            self._clear_buffer()
            self.active_changed.emit(False)
            self.failed.emit(f"音频设备播放失败（{error.name}），请检查系统输出设备")

    def _finish_playback(self) -> None:
        if not self._playing:
            return
        self._playing = False
        self._clear_buffer()
        self.active_changed.emit(False)
        self.finished.emit()

    def _clear_buffer(self) -> None:
        buffer = self._buffer
        self._buffer = None
        self._bytes = None
        if buffer is not None:
            buffer.close()
            buffer.deleteLater()

    def _dispose_sink(self) -> None:
        sink = self._sink
        if sink is not None:
            self._manual_stop = True
            sink.stop()
            self._manual_stop = False
            sink.deleteLater()
        self._sink = None
        self._format_key = None
        self._playing = False
        self._clear_buffer()


def _is_natural_completion(error: QAudio.Error, *, at_end: bool) -> bool:
    """Qt may report a drained short push buffer as an underrun on Windows."""

    return at_end and error in {QAudio.Error.NoError, QAudio.Error.UnderrunError}


__all__ = ["AudioPlaybackError", "PcmWavData", "PcmWavPlayer", "read_pcm16_wav"]
